# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: announcements.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import announcement_pb2 as announcement__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='announcements.proto',
  package='PluginAdapter.Api',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13\x61nnouncements.proto\x12\x11PluginAdapter.Api\x1a\x12\x61nnouncement.proto\"G\n\rAnnouncements\x12\x36\n\rannouncements\x18\x01 \x03(\x0b\x32\x1f.PluginAdapter.Api.Announcementb\x06proto3')
  ,
  dependencies=[announcement__pb2.DESCRIPTOR,])




_ANNOUNCEMENTS = _descriptor.Descriptor(
  name='Announcements',
  full_name='PluginAdapter.Api.Announcements',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='announcements', full_name='PluginAdapter.Api.Announcements.announcements', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=133,
)

_ANNOUNCEMENTS.fields_by_name['announcements'].message_type = announcement__pb2._ANNOUNCEMENT
DESCRIPTOR.message_types_by_name['Announcements'] = _ANNOUNCEMENTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Announcements = _reflection.GeneratedProtocolMessageType('Announcements', (_message.Message,), dict(
  DESCRIPTOR = _ANNOUNCEMENTS,
  __module__ = 'announcements_pb2'
  # @@protoc_insertion_point(class_scope:PluginAdapter.Api.Announcements)
  ))
_sym_db.RegisterMessage(Announcements)


# @@protoc_insertion_point(module_scope)
