# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: configuration.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='configuration.proto',
  package='PluginAdapter.Api',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13\x63onfiguration.proto\x12\x11PluginAdapter.Api\"\xc0\x01\n\rConfiguration\x12\x34\n\x05items\x18\x01 \x03(\x0b\x32%.PluginAdapter.Api.Configuration.Item\x1ay\n\x04Item\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x10\n\x06string\x18\x03 \x01(\tH\x00\x12\x11\n\x07integer\x18\x04 \x01(\x03H\x00\x12\x0f\n\x05\x66loat\x18\x05 \x01(\x02H\x00\x12\x11\n\x07\x62oolean\x18\x06 \x01(\x08H\x00\x42\x06\n\x04typeb\x06proto3')
)




_CONFIGURATION_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='PluginAdapter.Api.Configuration.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='PluginAdapter.Api.Configuration.Item.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='PluginAdapter.Api.Configuration.Item.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='string', full_name='PluginAdapter.Api.Configuration.Item.string', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='integer', full_name='PluginAdapter.Api.Configuration.Item.integer', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='float', full_name='PluginAdapter.Api.Configuration.Item.float', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='boolean', full_name='PluginAdapter.Api.Configuration.Item.boolean', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='type', full_name='PluginAdapter.Api.Configuration.Item.type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=114,
  serialized_end=235,
)

_CONFIGURATION = _descriptor.Descriptor(
  name='Configuration',
  full_name='PluginAdapter.Api.Configuration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='PluginAdapter.Api.Configuration.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CONFIGURATION_ITEM, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=235,
)

_CONFIGURATION_ITEM.containing_type = _CONFIGURATION
_CONFIGURATION_ITEM.oneofs_by_name['type'].fields.append(
  _CONFIGURATION_ITEM.fields_by_name['string'])
_CONFIGURATION_ITEM.fields_by_name['string'].containing_oneof = _CONFIGURATION_ITEM.oneofs_by_name['type']
_CONFIGURATION_ITEM.oneofs_by_name['type'].fields.append(
  _CONFIGURATION_ITEM.fields_by_name['integer'])
_CONFIGURATION_ITEM.fields_by_name['integer'].containing_oneof = _CONFIGURATION_ITEM.oneofs_by_name['type']
_CONFIGURATION_ITEM.oneofs_by_name['type'].fields.append(
  _CONFIGURATION_ITEM.fields_by_name['float'])
_CONFIGURATION_ITEM.fields_by_name['float'].containing_oneof = _CONFIGURATION_ITEM.oneofs_by_name['type']
_CONFIGURATION_ITEM.oneofs_by_name['type'].fields.append(
  _CONFIGURATION_ITEM.fields_by_name['boolean'])
_CONFIGURATION_ITEM.fields_by_name['boolean'].containing_oneof = _CONFIGURATION_ITEM.oneofs_by_name['type']
_CONFIGURATION.fields_by_name['items'].message_type = _CONFIGURATION_ITEM
DESCRIPTOR.message_types_by_name['Configuration'] = _CONFIGURATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Configuration = _reflection.GeneratedProtocolMessageType('Configuration', (_message.Message,), dict(

  Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), dict(
    DESCRIPTOR = _CONFIGURATION_ITEM,
    __module__ = 'configuration_pb2'
    # @@protoc_insertion_point(class_scope:PluginAdapter.Api.Configuration.Item)
    ))
  ,
  DESCRIPTOR = _CONFIGURATION,
  __module__ = 'configuration_pb2'
  # @@protoc_insertion_point(class_scope:PluginAdapter.Api.Configuration)
  ))
_sym_db.RegisterMessage(Configuration)
_sym_db.RegisterMessage(Configuration.Item)


# @@protoc_insertion_point(module_scope)
