# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: label.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='label.proto',
  package='PluginAdapter.Api',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0blabel.proto\x12\x11PluginAdapter.Api\"\xa1\x07\n\x05Label\x12\x30\n\x04type\x18\x01 \x01(\x0e\x32\".PluginAdapter.Api.Label.LabelType\x12\r\n\x05label\x18\x02 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x03 \x01(\t\x12\x36\n\nparameters\x18\x04 \x03(\x0b\x32\".PluginAdapter.Api.Label.Parameter\x12\x11\n\ttimestamp\x18\x05 \x01(\x04\x12\x16\n\x0ephysical_label\x18\x06 \x01(\x0c\x12\x16\n\x0e\x63orrelation_id\x18\x07 \x01(\x04\x1a\xa1\x05\n\tParameter\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x37\n\x05value\x18\x02 \x01(\x0b\x32(.PluginAdapter.Api.Label.Parameter.Value\x1a\xcc\x04\n\x05Value\x12\x10\n\x06string\x18\x01 \x01(\tH\x00\x12\x11\n\x07integer\x18\x02 \x01(\x03H\x00\x12\x11\n\x07\x64\x65\x63imal\x18\x03 \x01(\x01H\x00\x12\x11\n\x07\x62oolean\x18\x04 \x01(\x08H\x00\x12\x0e\n\x04\x64\x61te\x18\x05 \x01(\x04H\x00\x12\x0e\n\x04time\x18\t \x01(\x04H\x00\x12?\n\x05\x61rray\x18\x06 \x01(\x0b\x32..PluginAdapter.Api.Label.Parameter.Value.ArrayH\x00\x12?\n\x06struct\x18\x07 \x01(\x0b\x32-.PluginAdapter.Api.Label.Parameter.Value.HashH\x00\x12\x43\n\nhash_value\x18\x08 \x01(\x0b\x32-.PluginAdapter.Api.Label.Parameter.Value.HashH\x00\x1a\x41\n\x05\x41rray\x12\x38\n\x06values\x18\x01 \x03(\x0b\x32(.PluginAdapter.Api.Label.Parameter.Value\x1a\xc5\x01\n\x04Hash\x12\x44\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x33.PluginAdapter.Api.Label.Parameter.Value.Hash.Entry\x1aw\n\x05\x45ntry\x12\x35\n\x03key\x18\x01 \x01(\x0b\x32(.PluginAdapter.Api.Label.Parameter.Value\x12\x37\n\x05value\x18\x02 \x01(\x0b\x32(.PluginAdapter.Api.Label.Parameter.ValueB\x06\n\x04type\"\'\n\tLabelType\x12\x0c\n\x08STIMULUS\x10\x00\x12\x0c\n\x08RESPONSE\x10\x01\x62\x06proto3')
)



_LABEL_LABELTYPE = _descriptor.EnumDescriptor(
  name='LabelType',
  full_name='PluginAdapter.Api.Label.LabelType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STIMULUS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESPONSE', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=925,
  serialized_end=964,
)
_sym_db.RegisterEnumDescriptor(_LABEL_LABELTYPE)


_LABEL_PARAMETER_VALUE_ARRAY = _descriptor.Descriptor(
  name='Array',
  full_name='PluginAdapter.Api.Label.Parameter.Value.Array',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='PluginAdapter.Api.Label.Parameter.Value.Array.values', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=650,
  serialized_end=715,
)

_LABEL_PARAMETER_VALUE_HASH_ENTRY = _descriptor.Descriptor(
  name='Entry',
  full_name='PluginAdapter.Api.Label.Parameter.Value.Hash.Entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='PluginAdapter.Api.Label.Parameter.Value.Hash.Entry.key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='PluginAdapter.Api.Label.Parameter.Value.Hash.Entry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=796,
  serialized_end=915,
)

_LABEL_PARAMETER_VALUE_HASH = _descriptor.Descriptor(
  name='Hash',
  full_name='PluginAdapter.Api.Label.Parameter.Value.Hash',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='PluginAdapter.Api.Label.Parameter.Value.Hash.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_LABEL_PARAMETER_VALUE_HASH_ENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=718,
  serialized_end=915,
)

_LABEL_PARAMETER_VALUE = _descriptor.Descriptor(
  name='Value',
  full_name='PluginAdapter.Api.Label.Parameter.Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='string', full_name='PluginAdapter.Api.Label.Parameter.Value.string', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='integer', full_name='PluginAdapter.Api.Label.Parameter.Value.integer', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='decimal', full_name='PluginAdapter.Api.Label.Parameter.Value.decimal', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='boolean', full_name='PluginAdapter.Api.Label.Parameter.Value.boolean', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date', full_name='PluginAdapter.Api.Label.Parameter.Value.date', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='PluginAdapter.Api.Label.Parameter.Value.time', index=5,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='array', full_name='PluginAdapter.Api.Label.Parameter.Value.array', index=6,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='struct', full_name='PluginAdapter.Api.Label.Parameter.Value.struct', index=7,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hash_value', full_name='PluginAdapter.Api.Label.Parameter.Value.hash_value', index=8,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_LABEL_PARAMETER_VALUE_ARRAY, _LABEL_PARAMETER_VALUE_HASH, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='type', full_name='PluginAdapter.Api.Label.Parameter.Value.type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=335,
  serialized_end=923,
)

_LABEL_PARAMETER = _descriptor.Descriptor(
  name='Parameter',
  full_name='PluginAdapter.Api.Label.Parameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='PluginAdapter.Api.Label.Parameter.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='PluginAdapter.Api.Label.Parameter.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_LABEL_PARAMETER_VALUE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=923,
)

_LABEL = _descriptor.Descriptor(
  name='Label',
  full_name='PluginAdapter.Api.Label',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='PluginAdapter.Api.Label.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='PluginAdapter.Api.Label.label', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channel', full_name='PluginAdapter.Api.Label.channel', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='PluginAdapter.Api.Label.parameters', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='PluginAdapter.Api.Label.timestamp', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='physical_label', full_name='PluginAdapter.Api.Label.physical_label', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='correlation_id', full_name='PluginAdapter.Api.Label.correlation_id', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_LABEL_PARAMETER, ],
  enum_types=[
    _LABEL_LABELTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=964,
)

_LABEL_PARAMETER_VALUE_ARRAY.fields_by_name['values'].message_type = _LABEL_PARAMETER_VALUE
_LABEL_PARAMETER_VALUE_ARRAY.containing_type = _LABEL_PARAMETER_VALUE
_LABEL_PARAMETER_VALUE_HASH_ENTRY.fields_by_name['key'].message_type = _LABEL_PARAMETER_VALUE
_LABEL_PARAMETER_VALUE_HASH_ENTRY.fields_by_name['value'].message_type = _LABEL_PARAMETER_VALUE
_LABEL_PARAMETER_VALUE_HASH_ENTRY.containing_type = _LABEL_PARAMETER_VALUE_HASH
_LABEL_PARAMETER_VALUE_HASH.fields_by_name['entries'].message_type = _LABEL_PARAMETER_VALUE_HASH_ENTRY
_LABEL_PARAMETER_VALUE_HASH.containing_type = _LABEL_PARAMETER_VALUE
_LABEL_PARAMETER_VALUE.fields_by_name['array'].message_type = _LABEL_PARAMETER_VALUE_ARRAY
_LABEL_PARAMETER_VALUE.fields_by_name['struct'].message_type = _LABEL_PARAMETER_VALUE_HASH
_LABEL_PARAMETER_VALUE.fields_by_name['hash_value'].message_type = _LABEL_PARAMETER_VALUE_HASH
_LABEL_PARAMETER_VALUE.containing_type = _LABEL_PARAMETER
_LABEL_PARAMETER_VALUE.oneofs_by_name['type'].fields.append(
  _LABEL_PARAMETER_VALUE.fields_by_name['string'])
_LABEL_PARAMETER_VALUE.fields_by_name['string'].containing_oneof = _LABEL_PARAMETER_VALUE.oneofs_by_name['type']
_LABEL_PARAMETER_VALUE.oneofs_by_name['type'].fields.append(
  _LABEL_PARAMETER_VALUE.fields_by_name['integer'])
_LABEL_PARAMETER_VALUE.fields_by_name['integer'].containing_oneof = _LABEL_PARAMETER_VALUE.oneofs_by_name['type']
_LABEL_PARAMETER_VALUE.oneofs_by_name['type'].fields.append(
  _LABEL_PARAMETER_VALUE.fields_by_name['decimal'])
_LABEL_PARAMETER_VALUE.fields_by_name['decimal'].containing_oneof = _LABEL_PARAMETER_VALUE.oneofs_by_name['type']
_LABEL_PARAMETER_VALUE.oneofs_by_name['type'].fields.append(
  _LABEL_PARAMETER_VALUE.fields_by_name['boolean'])
_LABEL_PARAMETER_VALUE.fields_by_name['boolean'].containing_oneof = _LABEL_PARAMETER_VALUE.oneofs_by_name['type']
_LABEL_PARAMETER_VALUE.oneofs_by_name['type'].fields.append(
  _LABEL_PARAMETER_VALUE.fields_by_name['date'])
_LABEL_PARAMETER_VALUE.fields_by_name['date'].containing_oneof = _LABEL_PARAMETER_VALUE.oneofs_by_name['type']
_LABEL_PARAMETER_VALUE.oneofs_by_name['type'].fields.append(
  _LABEL_PARAMETER_VALUE.fields_by_name['time'])
_LABEL_PARAMETER_VALUE.fields_by_name['time'].containing_oneof = _LABEL_PARAMETER_VALUE.oneofs_by_name['type']
_LABEL_PARAMETER_VALUE.oneofs_by_name['type'].fields.append(
  _LABEL_PARAMETER_VALUE.fields_by_name['array'])
_LABEL_PARAMETER_VALUE.fields_by_name['array'].containing_oneof = _LABEL_PARAMETER_VALUE.oneofs_by_name['type']
_LABEL_PARAMETER_VALUE.oneofs_by_name['type'].fields.append(
  _LABEL_PARAMETER_VALUE.fields_by_name['struct'])
_LABEL_PARAMETER_VALUE.fields_by_name['struct'].containing_oneof = _LABEL_PARAMETER_VALUE.oneofs_by_name['type']
_LABEL_PARAMETER_VALUE.oneofs_by_name['type'].fields.append(
  _LABEL_PARAMETER_VALUE.fields_by_name['hash_value'])
_LABEL_PARAMETER_VALUE.fields_by_name['hash_value'].containing_oneof = _LABEL_PARAMETER_VALUE.oneofs_by_name['type']
_LABEL_PARAMETER.fields_by_name['value'].message_type = _LABEL_PARAMETER_VALUE
_LABEL_PARAMETER.containing_type = _LABEL
_LABEL.fields_by_name['type'].enum_type = _LABEL_LABELTYPE
_LABEL.fields_by_name['parameters'].message_type = _LABEL_PARAMETER
_LABEL_LABELTYPE.containing_type = _LABEL
DESCRIPTOR.message_types_by_name['Label'] = _LABEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Label = _reflection.GeneratedProtocolMessageType('Label', (_message.Message,), dict(

  Parameter = _reflection.GeneratedProtocolMessageType('Parameter', (_message.Message,), dict(

    Value = _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), dict(

      Array = _reflection.GeneratedProtocolMessageType('Array', (_message.Message,), dict(
        DESCRIPTOR = _LABEL_PARAMETER_VALUE_ARRAY,
        __module__ = 'label_pb2'
        # @@protoc_insertion_point(class_scope:PluginAdapter.Api.Label.Parameter.Value.Array)
        ))
      ,

      Hash = _reflection.GeneratedProtocolMessageType('Hash', (_message.Message,), dict(

        Entry = _reflection.GeneratedProtocolMessageType('Entry', (_message.Message,), dict(
          DESCRIPTOR = _LABEL_PARAMETER_VALUE_HASH_ENTRY,
          __module__ = 'label_pb2'
          # @@protoc_insertion_point(class_scope:PluginAdapter.Api.Label.Parameter.Value.Hash.Entry)
          ))
        ,
        DESCRIPTOR = _LABEL_PARAMETER_VALUE_HASH,
        __module__ = 'label_pb2'
        # @@protoc_insertion_point(class_scope:PluginAdapter.Api.Label.Parameter.Value.Hash)
        ))
      ,
      DESCRIPTOR = _LABEL_PARAMETER_VALUE,
      __module__ = 'label_pb2'
      # @@protoc_insertion_point(class_scope:PluginAdapter.Api.Label.Parameter.Value)
      ))
    ,
    DESCRIPTOR = _LABEL_PARAMETER,
    __module__ = 'label_pb2'
    # @@protoc_insertion_point(class_scope:PluginAdapter.Api.Label.Parameter)
    ))
  ,
  DESCRIPTOR = _LABEL,
  __module__ = 'label_pb2'
  # @@protoc_insertion_point(class_scope:PluginAdapter.Api.Label)
  ))
_sym_db.RegisterMessage(Label)
_sym_db.RegisterMessage(Label.Parameter)
_sym_db.RegisterMessage(Label.Parameter.Value)
_sym_db.RegisterMessage(Label.Parameter.Value.Array)
_sym_db.RegisterMessage(Label.Parameter.Value.Hash)
_sym_db.RegisterMessage(Label.Parameter.Value.Hash.Entry)


# @@protoc_insertion_point(module_scope)
