# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import label_pb2 as label__pb2
import announcement_pb2 as announcement__pb2
import configuration_pb2 as configuration__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='PluginAdapter.Api',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rmessage.proto\x12\x11PluginAdapter.Api\x1a\x0blabel.proto\x1a\x12\x61nnouncement.proto\x1a\x13\x63onfiguration.proto\"\xf5\x02\n\x07Message\x12\x31\n\x05\x65rror\x18\x01 \x01(\x0b\x32 .PluginAdapter.Api.Message.ErrorH\x00\x12\x37\n\x0c\x61nnouncement\x18\x02 \x01(\x0b\x32\x1f.PluginAdapter.Api.AnnouncementH\x00\x12\x39\n\rconfiguration\x18\x03 \x01(\x0b\x32 .PluginAdapter.Api.ConfigurationH\x00\x12)\n\x05label\x18\x04 \x01(\x0b\x32\x18.PluginAdapter.Api.LabelH\x00\x12\x31\n\x05reset\x18\x05 \x01(\x0b\x32 .PluginAdapter.Api.Message.ResetH\x00\x12\x31\n\x05ready\x18\x06 \x01(\x0b\x32 .PluginAdapter.Api.Message.ReadyH\x00\x1a\x07\n\x05Reset\x1a\x07\n\x05Ready\x1a\x18\n\x05\x45rror\x12\x0f\n\x07message\x18\x01 \x01(\tB\x06\n\x04typeb\x06proto3')
  ,
  dependencies=[label__pb2.DESCRIPTOR,announcement__pb2.DESCRIPTOR,configuration__pb2.DESCRIPTOR,])




_MESSAGE_RESET = _descriptor.Descriptor(
  name='Reset',
  full_name='PluginAdapter.Api.Message.Reset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=414,
  serialized_end=421,
)

_MESSAGE_READY = _descriptor.Descriptor(
  name='Ready',
  full_name='PluginAdapter.Api.Message.Ready',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=423,
  serialized_end=430,
)

_MESSAGE_ERROR = _descriptor.Descriptor(
  name='Error',
  full_name='PluginAdapter.Api.Message.Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='PluginAdapter.Api.Message.Error.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=432,
  serialized_end=456,
)

_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='PluginAdapter.Api.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='PluginAdapter.Api.Message.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='announcement', full_name='PluginAdapter.Api.Message.announcement', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='configuration', full_name='PluginAdapter.Api.Message.configuration', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='PluginAdapter.Api.Message.label', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reset', full_name='PluginAdapter.Api.Message.reset', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ready', full_name='PluginAdapter.Api.Message.ready', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MESSAGE_RESET, _MESSAGE_READY, _MESSAGE_ERROR, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='type', full_name='PluginAdapter.Api.Message.type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=91,
  serialized_end=464,
)

_MESSAGE_RESET.containing_type = _MESSAGE
_MESSAGE_READY.containing_type = _MESSAGE
_MESSAGE_ERROR.containing_type = _MESSAGE
_MESSAGE.fields_by_name['error'].message_type = _MESSAGE_ERROR
_MESSAGE.fields_by_name['announcement'].message_type = announcement__pb2._ANNOUNCEMENT
_MESSAGE.fields_by_name['configuration'].message_type = configuration__pb2._CONFIGURATION
_MESSAGE.fields_by_name['label'].message_type = label__pb2._LABEL
_MESSAGE.fields_by_name['reset'].message_type = _MESSAGE_RESET
_MESSAGE.fields_by_name['ready'].message_type = _MESSAGE_READY
_MESSAGE.oneofs_by_name['type'].fields.append(
  _MESSAGE.fields_by_name['error'])
_MESSAGE.fields_by_name['error'].containing_oneof = _MESSAGE.oneofs_by_name['type']
_MESSAGE.oneofs_by_name['type'].fields.append(
  _MESSAGE.fields_by_name['announcement'])
_MESSAGE.fields_by_name['announcement'].containing_oneof = _MESSAGE.oneofs_by_name['type']
_MESSAGE.oneofs_by_name['type'].fields.append(
  _MESSAGE.fields_by_name['configuration'])
_MESSAGE.fields_by_name['configuration'].containing_oneof = _MESSAGE.oneofs_by_name['type']
_MESSAGE.oneofs_by_name['type'].fields.append(
  _MESSAGE.fields_by_name['label'])
_MESSAGE.fields_by_name['label'].containing_oneof = _MESSAGE.oneofs_by_name['type']
_MESSAGE.oneofs_by_name['type'].fields.append(
  _MESSAGE.fields_by_name['reset'])
_MESSAGE.fields_by_name['reset'].containing_oneof = _MESSAGE.oneofs_by_name['type']
_MESSAGE.oneofs_by_name['type'].fields.append(
  _MESSAGE.fields_by_name['ready'])
_MESSAGE.fields_by_name['ready'].containing_oneof = _MESSAGE.oneofs_by_name['type']
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(

  Reset = _reflection.GeneratedProtocolMessageType('Reset', (_message.Message,), dict(
    DESCRIPTOR = _MESSAGE_RESET,
    __module__ = 'message_pb2'
    # @@protoc_insertion_point(class_scope:PluginAdapter.Api.Message.Reset)
    ))
  ,

  Ready = _reflection.GeneratedProtocolMessageType('Ready', (_message.Message,), dict(
    DESCRIPTOR = _MESSAGE_READY,
    __module__ = 'message_pb2'
    # @@protoc_insertion_point(class_scope:PluginAdapter.Api.Message.Ready)
    ))
  ,

  Error = _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), dict(
    DESCRIPTOR = _MESSAGE_ERROR,
    __module__ = 'message_pb2'
    # @@protoc_insertion_point(class_scope:PluginAdapter.Api.Message.Error)
    ))
  ,
  DESCRIPTOR = _MESSAGE,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:PluginAdapter.Api.Message)
  ))
_sym_db.RegisterMessage(Message)
_sym_db.RegisterMessage(Message.Reset)
_sym_db.RegisterMessage(Message.Ready)
_sym_db.RegisterMessage(Message.Error)


# @@protoc_insertion_point(module_scope)
